Remove class preloads related to Log4j2 async loggers
Log4j2 async logging uses an optional dependency that users are supposed to explicitly opt in to, so preloading those classes causes a NoClassDefFoundError.

I don't know how this even ended up in the initial class load logs, but we shouldn't be trying to load it.